<?php

session_start();

require_once "../config.php";
require_once "../vendor/autoload.php";

use Dompdf\Dompdf;

if (!isset($_SESSION['user_id'])) {
    header("Location: ../login.php");
    exit();
}

if (!isset($_GET['id'])) {
    die("Invalid Request");
}

$id = intval($_GET['id']);

$sql = "SELECT * FROM resumes
        WHERE id='$id'
        AND user_id='".$_SESSION['user_id']."'";

$result = mysqli_query($conn,$sql);

if(mysqli_num_rows($result)==0){
    die("Report not found.");
}

$row = mysqli_fetch_assoc($result);

$userName = $_SESSION['user_name'];

$resumeFile = $row['resume_file'];

$feedback = htmlspecialchars($row['ai_feedback']);

$feedback = preg_replace(
'/^(ATS SCORE:|PROFESSIONAL SUMMARY:|STRENGTHS:|WEAKNESSES:|MISSING TECHNICAL SKILLS:|MISSING SOFT SKILLS:|ATS KEYWORDS TO ADD:|GRAMMAR ISSUES:|FORMATTING ISSUES:|PROJECTS REVIEW:|EXPERIENCE REVIEW:|EDUCATION REVIEW:|INTERVIEW READINESS:|FINAL RECOMMENDATION:)/mi',
'<h2>$1</h2>',
$feedback
);

$feedback = nl2br($feedback);

$html = "

<!DOCTYPE html>

<html>

<head>

<style>

body{

font-family:DejaVu Sans;

padding:35px;

color:#334155;

line-height:1.8;

}

.header{

background:linear-gradient(90deg,#2563EB,#7C3AED);

background:#2563EB;

padding:25px;

color:white;

text-align:center;

border-radius:12px;

}

.header h1{

margin:0;

font-size:34px;

}

.header p{

margin-top:8px;

font-size:16px;

}

.info{

margin-top:30px;

width:100%;

border-collapse:collapse;

}

.info td{

padding:10px;

border-bottom:1px solid #ddd;

}

.score{

margin:35px 0;

text-align:center;

background:#EEF4FF;

padding:20px;

border-radius:12px;

border:2px solid #2563EB;

}

.score h2{

margin:0;

color:#2563EB;

font-size:22px;

}

.score span{

font-size:42px;

font-weight:bold;

color:#7C3AED;

}

.content{

margin-top:25px;

}

.content h2{

background:#2563EB;

color:white;

padding:8px 15px;

border-radius:8px;

font-size:18px;

margin-top:28px;

}

.footer{

margin-top:50px;

text-align:center;

font-size:13px;

color:#777;

}

</style>

</head>

<body>

<div class='header'>

<h1>CareerPilot AI</h1>

<p>Professional Resume Analysis Report</p>

</div>

<table class='info'>

<tr>

<td><strong>Candidate</strong></td>

<td>$userName</td>

</tr>

<tr>

<td><strong>Resume</strong></td>

<td>$resumeFile</td>

</tr>

<tr>

<td><strong>Date</strong></td>

<td>".date("d M Y")."</td>

</tr>

</table>

<div class='score'>

<h2>AI Resume Analysis</h2>

<span>Generated Successfully</span>

</div>

<div class='content'>

$feedback

</div>

<div class='footer'>

Generated by CareerPilot AI<br>

AI Powered Career Assistant

</div>

</body>

</html>

";

$dompdf = new Dompdf();

$dompdf->loadHtml($html);

$dompdf->setPaper("A4","portrait");

$dompdf->render();

$dompdf->stream(
"CareerPilot_Resume_Report.pdf",
["Attachment"=>true]
);

exit();

?>